[package]
name = "botgen"
version = "0.1.0"
authors = ["Jacob Swart <zenerboson@gmail.com>"]
edition = "2018"

[dependencies]
askama = "0.7.2"
pulldown-cmark = "0.2.0"
chrono = "0.4.6"
html-minifier = "1.1.4"
base64 = "0.10.1"
mime_guess = "1.8.6"
argparse = "0.2.2"
